/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"404" | "alarm" | "alert_cur" | "alert_his" | "alert_manager" | "alert_rule" | "api" | "bug" | "component" | "dashboard" | "datasource" | "dispatch_rule" | "escalation_config" | "escalation_step" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "link" | "lock" | "menu" | "model-one" | "model" | "notify_escalation" | "notify_manager" | "notify_template" | "order-center" | "order-convert" | "order-list" | "process-control" | "process" | "relation-graph" | "relation-type" | "resource" | "role" | "runner" | "schedule" | "search" | "submit-order" | "task-history" | "task-manager" | "task" | "team" | "template" | "template_set" | "time_series" | "unocss" | "user" | "worker" | "workspace">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"404" | "alarm" | "alert_cur" | "alert_his" | "alert_manager" | "alert_rule" | "api" | "bug" | "component" | "dashboard" | "datasource" | "dispatch_rule" | "escalation_config" | "escalation_step" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "link" | "lock" | "menu" | "model-one" | "model" | "notify_escalation" | "notify_manager" | "notify_template" | "order-center" | "order-convert" | "order-list" | "process-control" | "process" | "relation-graph" | "relation-type" | "resource" | "role" | "runner" | "schedule" | "search" | "submit-order" | "task-history" | "task-manager" | "task" | "team" | "template" | "template_set" | "time_series" | "unocss" | "user" | "worker" | "workspace">;
          default: string;
          required: true;
      };
  }>>, {
      name: "404" | "alarm" | "alert_cur" | "alert_his" | "alert_manager" | "alert_rule" | "api" | "bug" | "component" | "dashboard" | "datasource" | "dispatch_rule" | "escalation_config" | "escalation_step" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "link" | "lock" | "menu" | "model-one" | "model" | "notify_escalation" | "notify_manager" | "notify_template" | "order-center" | "order-convert" | "order-list" | "process-control" | "process" | "relation-graph" | "relation-type" | "resource" | "role" | "runner" | "schedule" | "search" | "submit-order" | "task-history" | "task-manager" | "task" | "team" | "template" | "template_set" | "time_series" | "unocss" | "user" | "worker" | "workspace";
  }>;
  export const svgNames: ["404", "alarm", "alert_cur", "alert_his", "alert_manager", "alert_rule", "api", "bug", "component", "dashboard", "datasource", "dispatch_rule", "escalation_config", "escalation_step", "fullscreen-exit", "fullscreen", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "link", "lock", "menu", "model-one", "model", "notify_escalation", "notify_manager", "notify_template", "order-center", "order-convert", "order-list", "process-control", "process", "relation-graph", "relation-type", "resource", "role", "runner", "schedule", "search", "submit-order", "task-history", "task-manager", "task", "team", "template", "template_set", "time_series", "unocss", "user", "worker", "workspace"];
  export type SvgName = "404" | "alarm" | "alert_cur" | "alert_his" | "alert_manager" | "alert_rule" | "api" | "bug" | "component" | "dashboard" | "datasource" | "dispatch_rule" | "escalation_config" | "escalation_step" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "link" | "lock" | "menu" | "model-one" | "model" | "notify_escalation" | "notify_manager" | "notify_template" | "order-center" | "order-convert" | "order-list" | "process-control" | "process" | "relation-graph" | "relation-type" | "resource" | "role" | "runner" | "schedule" | "search" | "submit-order" | "task-history" | "task-manager" | "task" | "team" | "template" | "template_set" | "time_series" | "unocss" | "user" | "worker" | "workspace";
  export default SvgIcon;
}
